### ISSUE TITLE
Error compilation with Typescript

### ISSUE THREAD

**Issue by ashishpatel0720** [Airfooox/cron-validate#177]
When I am trying to compile my project after adding **cron-validate** as dependency,
I am getting typescript error.

![image](https://user-images.githubusercontent.com/16856802/111894583-f39b3d80-8a31-11eb-8227-4e4105fc12ef.png)

**Comment by GuillaumeRochat** [comment]
@ashishpatel0720 Is your typescript version below 3.8 by any chance? They introduced that syntax in 3.8 : https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

**Comment by ashishpatel0720** [comment]
Yes it's typescript@3.6.

Is there any way to remove this error,
May be using older version for this dependency.

**Comment by GuillaumeRochat** [comment]
@ashishpatel0720 Have you tried updating your typescript version? Or downgrading the library version, maybe to something like 1.1.5?

**Comment by NevenLiang** [comment]
@GuillaumeRochat 

> ERROR in The Angular Compiler requires TypeScript >=3.4.0 and <3.6.0 but 3.8.3 was found instead.

I have tried to upgrade typescript in Angular 8, but it has a dependency on typescript in old version. I have also tried `cron-validate@1.1.5`, but it seems missing lots of feature in the latest one, like 

- Missing 'npm-cron-node' preset
- Do not support the abbreviation of months and days of week. 


Is it possible to make it work in `cron-validate@1.1.5`.

Thanks!

**Comment by GuillaumeRochat** [comment]
That would mean building a newer version without that syntax on the project. Forget about the version 1.1.5, it seems to have already been there for even longer upon further search. My mistake.

@Airfooox what are your thoughts on removing this syntax? I don't see a way to specify the typescript version of the declaration file output in the lib directory.

**Comment by Airfooox** [comment]
I'll see what I can do to make it work with lower TypeScript version.

Sorry for not responding sooner, didnt get a notification somehow.

**Comment by Airfooox** [comment]
I removed all of the `import type` - should work now

**Comment by Airfooox** [comment]
:tada: This issue is resolved in version 1.4.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/cron-validate/v/1.4.3)
- [GitHub release](https://github.com/Airfooox/cron-validate/releases/tag/v1.4.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by ashishpatel0720** [comment]
Thanks, @GuillaumeRochat @Airfooox @NevenLiang from prompt reply and suggestion.
Closing this issue as this has been resolved in v1.4.3 📦🚀
