### ISSUE TITLE
Isn't up to date with AWS

### ISSUE THREAD

**Issue by shellscape** [Airfooox/cron-validate#224]
Using the latest version on NPM (v1.3.1), the package doesn't properly validate AWS cloudwatch scheduling crons. 

`*/5 * ? * *` is valid, but returns `false`. `*/5 * * * *` isn't valid but returns `true`

**Comment by Airfooox** [comment]
I'll take a look at it

**Comment by Airfooox** [comment]
Both should be invalid because they only got 5 fields and aws cloudwatch uses 6. This works with my testing. Can you give me the exact code lines you've used?
