### ISSUE TITLE
Day of week number can't be bigger than 5

### ISSUE THREAD

**Issue by dalex-am** [Airfooox/cron-validate#263]
https://github.com/Airfooox/cron-validate/blob/b6963fc30ab9b17b32f705b256d6234e7fac6cad/src/helper.ts#L151

Can you add one more condition into "if"?

**Comment by Airfooox** [comment]
I don't quite know what you mean. The dayof the week can't be greater than 5? Why not?

**Comment by dalex-am** [comment]
I mean value "1#8" equals to 8th monday of months. Max count of any DOW cannot be greater than 5 just because of calendar structure. Write [here](https://www.freeformatter.com/cron-expression-generator-quartz.html) "* * * ? * 3#8 *"

**Comment by Airfooox** [comment]
Fixed this in version 1.4.5, thanks bringing up the issue!

**Comment by Airfooox** [comment]
Fixed this in version 1.4.5, thanks bringing up the issue!
