### ISSUE TITLE
Alias support

### ISSUE THREAD

**Issue by niftylettuce** [Airfooox/cron-validate#67]
Can you add alias support like https://github.com/TheCloudConnectors/cron-validator has?

**Comment by niftylettuce** [comment]
Now using this in @breejs!

https://github.com/breejs/bree

**Comment by Airfooox** [comment]
Hey, I had already planned to support alias, but havnt got the time to do it.

I'll try my best and try to get it done next week.

**Comment by niftylettuce** [comment]
❤️

**Comment by GuillaumeRochat** [comment]
FYI, I will try to backport that feature into this lib once https://github.com/Airfooox/cron-validate/pull/80 is merged. There are a couple of gotcha with the alias that I found while doing the feature in cron-validator.

**Comment by GuillaumeRochat** [comment]
Turns out it was much easier than I expected this time around.

**Comment by niftylettuce** [comment]
Thank you!
