### ISSUE TITLE
Please support normal JavaScript require

### ISSUE THREAD

**Issue by niftylettuce** [Airfooox/cron-validate#69]
Hello,

Since this is a node.js package, you should support standard `require` syntax support (not ES module only).

Please export a default function so that we don't have to do this, which is very non-standard:

```js
const cron = require('cron-validate').default;
```

It should just be:

```js
const cron = require('cron-validate');
```

**Comment by Airfooox** [comment]
Should be fixed. If not or anything else is not working correctly, let me know.

**Comment by niftylettuce** [comment]
Thank you @Airfooox 

Btw, using this in Bree!

https://jobscheduler.net

Would love a Bree mention in your README!
